version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    volumes:
      - ./.docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
  server:
    image: node:18-alpine
    ports:
      - '10007:3000'
    volumes:
      - ./:/usr/app
    working_dir: /usr/app/
    command: npm start